### ISSUE TITLE
Statistics UI and REST service requirements

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/KV006#6]

**Comment by Huralnyk** [comment]
Should create 2 views. The first one with TableView for different TOP's of problems. The second one for general statistics with a Pie Chart. Hardcode all of this. Consider about hierarchy of Type objects, about Ecomap API.

**Comment by Huralnyk** [comment]
The Top Chart Table View view and its controller have been created, XYPieChart library has been chosen to implement General Stats view. Ecomap fetcher were expanded.
